### ISSUE TITLE
Having trouble running code

### ISSUE THREAD

**Issue by dgenin** [chrismurrph/plc-parser#1]
Thank you so much for putting this together. I am very new to Clojure and so maybe doing something foolish. Please, forgive me in this case.

I am expecting that the project could be run with ``lien run``. However, this command gives

    $ lein run
    Can't find 'parser.core' as .class or .clj for lein run: please check the spelling.
    Exception in thread "main" java.io.FileNotFoundException: Could not locate parser/core__init.class or parser/core.clj on classpath., compiling:(/private/var/folders/32/ywvftjnd3vg3lgstr_hz8wqmcbvldv/T/form-init6005333129281096486.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
     Caused by: java.io.FileNotFoundException: Could not locate parser/core__init.class or parser/core.clj on classpath.
	at clojure.lang.RT.load(RT.java:456)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval1347$fn__1349.invoke(form-init6005333129281096486.clj:1)
	at user$eval1347.invokeStatic(form-init6005333129281096486.clj:1)
	at user$eval1347.invoke(form-init6005333129281096486.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more

I am running on OS X High Sierra in case this is relevant.

**Comment by chrismurrph** [comment]
Tomorrow I'll write up a README that says how to run that project. But it is through the REPL. Take a look at `user.clj`.

**Comment by dgenin** [comment]
Thank you!

**Comment by chrismurrph** [comment]
Closing this, assuming you can now run it at the REPL.
